version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7    
    commands:
      - apt-get update -y
      - apt-get install -y pandoc
      - pandoc --version
  build:
    commands:
      - echo building the project
      - git config --global user.email "wjeong@gmai.com"
      - git config --global user.name "Wayland Jeong" 
      - git help -a | grep credential-
      - GITHELPER=`git help -a | grep credential- | head -n1 | awk '{print $1;}'`
      - git help ${GITHELPER}
      - git remote -v
      - pandoc -s -o README.doc README.md
      - git add README.doc
      - git commit -m "Converted markdown to doc using pandoc"
      - git push -u origin master  
  post_build:
    commands:
      - echo post build phase
