version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7    
    commands:
      - apt-get update -y
      - apt-get install -y pandoc
      - pandoc --version
  build:
    commands:
      - echo building the project
      - git remote -v
      - pandoc -s -o README.doc README.md
      - git add README.doc
      - git commit -m "Converted markdown to doc using pandoc"
      - git push -u origin master  
  post_build:
    commands:
      - echo post build phase
