version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7    
    commands:
      - sudo apt-get update && sudo apt-get install pandoc
      - pandoc --version
  build:
    commands:
      - echo building the project
      - git remote -v
  post_build:
    commands:
      - echo post build phase
