version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7    
    commands:
      - apt-get update -y
      - apt-get install -y pandoc
      - pandoc --version
  build:
    commands:
      - echo building the project
      - git remote -v
  post_build:
    commands:
      - echo post build phase
