version: 0.2

env:
  parameter-store:
    GITHUB_PAT: "GithubPersonalAccessToken"
    
phases:
  install:
    runtime-versions:
      python: 3.7    
    commands:
      - apt-get update -y
      - apt-get install -y pandoc
      - pandoc --version
  build:
    commands:
      - echo building the project
      - git config --global credential.helper store
      - echo "https://waylandjeong:${GITHUB_PAT}@github.com" > $HOME/.git-credentials
      - git config --global user.email "wjeong@gmai.com"
      - git config --global user.name "Wayland Jeong"
      - git remote -v
      - pandoc -s -o README.doc README.md
      - git remote prune origin
      - git fsck
      - git add README.doc
      - git commit -m "Converted markdown to doc using pandoc"
      - git push -u origin master
  post_build:
    commands:
      - echo post build phase
