version: 0.1

phases:
  install:
    runtime-versions:
      python: 3.7    
    commands:
      - printenv
  build:
    commands:
      - echo building the project
  post_build:
    commands:
      - echo post build phase
